"""Kadermanager"""
DOMAIN = "kadermanager"
ATTRIBUTION = "Data provided by kadermanager.de"

CONF_TEAM_NAME = "teamname"
CONF_USERNAME = "username"
CONF_PASSWORD = "password"
CONF_EVENT_LIMIT = "event_limit"
CONF_UPDATE_INTERVAL = "update_interval"
CONF_FETCH_PLAYER_INFO = "fetch_player_info"
CONF_FETCH_COMMENTS = "fetch_comments"
ATTR_DATA = "data"
